spring.application.name=backend

spring.datasource.url=postgres_url
spring.datasource.username=username
spring.datasource.password=password

jwt.secret=jwt_secret_key
jwt.expiration=86400000
jwt.refresh-expiration=604800000

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080

logging.level.com.legacylock.backend.service.ReleaseSchedulerService=INFO

spring.security.oauth2.client.registration.google.client-id=google_client_id
spring.security.oauth2.client.registration.google.client-secret=google_app_password
spring.security.oauth2.client.registration.google.scope=openid,email,profile

app.oauth2.redirect-url=frontend_url

aws.region=aws_s3_bucket_region
aws.s3.bucket=bucket_name

aws.access-key=aws_access_key
aws.secret-key=aws_secret_key

app.encryption.secret=encryption_key
app.encryption.algorithm=AES/GCM/NoPadding

spring.profiles.active=dev
