spring.application.name=backend

spring.datasource.url=postgres_database_url
spring.datasource.username=database_username
spring.datasource.password=database_password

jwt.secret=jwt_secret_key
jwt.expiration=86400000
jwt.refresh-expiration=604800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080

logging.level.com.legacylock.backend.service.ReleaseSchedulerService=INFO

spring.security.oauth2.client.registration.google.client-id=google_client_id
spring.security.oauth2.client.registration.google.client-secret=google_oauth_password
spring.security.oauth2.client.registration.google.scope=openid,email,profile

app.oauth2.redirect-url=frontend_redirect_url

aws.region=aws_s3_bucket_region
aws.s3.bucket=aws_s3_bucket_name

aws.access-key=aws_access_key
aws.secret-key=aws_secret_key

app.encryption.secret=encryption_key
app.encryption.algorithm=AES/GCM/NoPadding

spring.profiles.active=dev

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mail_transfer_email
spring.mail.password=google_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.enabled=true
app.frontend.url=frontend_url

app.email-verification.expiration-minutes=30
app.password-reset.expiration-minutes=15
