package com.legacylock.backend.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    TOKEN_REFRESHED,

    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    PASSWORD_RESET_EMAIL_SENT,
    PASSWORD_RESET_COMPLETED,

    RECEIVER_CREATED,
    RECEIVER_UPDATED,
    RECEIVER_REMOVED,

    CAPSULE_CREATED,
    CAPSULE_UPDATED,
    CAPSULE_ACTIVATED,
    CAPSULE_DELETED,

    CAPSULE_FILE_UPLOADED,
    CAPSULE_FILE_DELETED,
    CAPSULE_FILE_DOWNLOADED_BY_RECEIVER,

    RECEIVER_ASSIGNED_TO_CAPSULE,
    RECEIVER_REMOVED_FROM_CAPSULE,

    RELEASE_POLICY_CREATED,
    RELEASE_POLICY_UPDATED,
    RELEASE_POLICY_PAUSED,
    RELEASE_POLICY_ACTIVATED,

    CHECK_IN_CREATED,

    OWNER_REMINDER_EMAIL_SENT,

    CAPSULE_RELEASED,
    ACCESS_GRANTED,

    CAPSULE_VIEWED_BY_RECEIVER,
    CAPSULE_ACKNOWLEDGED
}
